cc_binary(
    name = "hello_world",
    srcs = [
        "helloworld.c",
    ],
    deps = [
    ],
)

cc_binary(
    name = "copy",
    srcs = [
        "copy.c",
    ],
    deps = [
    ],
)

cc_binary(
    name = "fahrenheit",
    srcs = [
        "fahrenheit.c",
    ],
    deps = [
    ],
)
