cc_binary(
    name = "hello_world",
    srcs = [
        "helloworld.c",
    ],
    deps = [
    ],
)

cc_binary(
    name = "farenheit",
    srcs = [
        "fahrenheit.c",
    ],
    deps = [
    ],
)
